/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uet;


import com.uet.model.PersonEntity;
import com.uet.service.PersonService;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;

/**
 *
 * @author hungpt
 */
public class ManageStorage extends javax.swing.JFrame {

    /**
     * Creates new form ManageStorage
     */
    public ManageStorage() {
        initData();
        initComponents();
        this.changeView(this.itemMenu);
    }

    private void initData() {
        try {
            providerService = new PersonService("provider.txt");
            providers = providerService.convertData();
            customerService = new PersonService("customer.txt");
            customers = customerService.convertData();
            customerObj = customerService.generateProviderObject();
        } catch (Exception e){
            System.out.println("Error");
        }
    }
    
    private void changeView(JPanel panel){
        this.itemMenu.setVisible(false);
        this.storageMenu.setVisible(false);
        this.exportMenu.setVisible(false);
        this.customerMenu.setVisible(false);
        this.providerMenu.setVisible(false);
        this.statisticMenu.setVisible(false);
        if(panel != null) {
            panel.setVisible(true);
        }
    }

    private Object[][] customerObj;
    private void renderCustomerTable(){
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
                customerObj,
                new String [] {
                        "STT", "Tên", "Địa chỉ", "Số điện thoại", "Ngày tạo", "Tổng tiền", "Ghi chú"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemBtn = new javax.swing.JButton();
        importBtn = new javax.swing.JButton();
        exportBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();
        providerBtn = new javax.swing.JButton();
        statisticBtn = new javax.swing.JButton();
        itemMenu = new javax.swing.JPanel();
        nameInput = new javax.swing.JTextField();
        itemLabel = new javax.swing.JLabel();
        itemCodeInput = new javax.swing.JTextField();
        codeLabel = new javax.swing.JLabel();
        typeItem = new javax.swing.JComboBox<>();
        typeLabel = new javax.swing.JLabel();
        providerComp = new javax.swing.JComboBox<>();
        providerLabel = new javax.swing.JLabel();
        moneyImportInput = new javax.swing.JTextField();
        moneyImportLabel = new javax.swing.JLabel();
        moneyExportInput = new javax.swing.JTextField();
        moneyExportLabel = new javax.swing.JLabel();
        noteInput = new javax.swing.JTextField();
        noteLabel = new javax.swing.JLabel();
        addItemBtn = new javax.swing.JButton();
        editItemBtn = new javax.swing.JButton();
        deleteItemBtn = new javax.swing.JButton();
        itemTableContainer = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        storageMenu = new javax.swing.JPanel();
        itemListStorage = new javax.swing.JComboBox<>();
        itemListLabel = new javax.swing.JLabel();
        codeListStorage = new javax.swing.JComboBox<>();
        quantityInputStorage = new javax.swing.JTextField();
        codeListLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        providerList = new javax.swing.JComboBox<>();
        providerStorageLabel = new javax.swing.JLabel();
        storeBtn = new javax.swing.JButton();
        editStorageBtn = new javax.swing.JButton();
        deleteItemStorageBtn = new javax.swing.JButton();
        importContainer = new javax.swing.JScrollPane();
        importTable = new javax.swing.JTable();
        exportMenu = new javax.swing.JPanel();
        itemLabel1 = new javax.swing.JLabel();
        codeLabel1 = new javax.swing.JLabel();
        typeLabel1 = new javax.swing.JLabel();
        providerLabel1 = new javax.swing.JLabel();
        addExportBtn = new javax.swing.JButton();
        editExportBtn = new javax.swing.JButton();
        deleteExportBtn = new javax.swing.JButton();
        exportTableContainer = new javax.swing.JScrollPane();
        exportTable = new javax.swing.JTable();
        nameItemExportCom = new javax.swing.JComboBox<>();
        codeExportCom = new javax.swing.JComboBox<>();
        customerExportCom = new javax.swing.JComboBox<>();
        quantityExportInput = new javax.swing.JTextField();
        customerMenu = new javax.swing.JPanel();
        nameCustomerInput = new javax.swing.JTextField();
        itemLabel2 = new javax.swing.JLabel();
        addressCustomerInput = new javax.swing.JTextField();
        codeLabel2 = new javax.swing.JLabel();
        typeLabel2 = new javax.swing.JLabel();
        providerLabel2 = new javax.swing.JLabel();
        phoneCustomertInput = new javax.swing.JTextField();
        noteCustomerInput = new javax.swing.JTextField();
        addCustomerBtn = new javax.swing.JButton();
        editCustomerBtn = new javax.swing.JButton();
        deleteCustomerBtn = new javax.swing.JButton();
        customerTableContainer = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        providerMenu = new javax.swing.JPanel();
        nameProviderInput = new javax.swing.JTextField();
        itemLabel4 = new javax.swing.JLabel();
        addressProviderInput = new javax.swing.JTextField();
        codeLabel4 = new javax.swing.JLabel();
        typeLabel4 = new javax.swing.JLabel();
        providerLabel4 = new javax.swing.JLabel();
        phoneProviderInput = new javax.swing.JTextField();
        noteProviderInput = new javax.swing.JTextField();
        addProviderBtn = new javax.swing.JButton();
        editProviderBtn = new javax.swing.JButton();
        deleteProviderBtn = new javax.swing.JButton();
        providerTableContainer = new javax.swing.JScrollPane();
        providerTable = new javax.swing.JTable();
        statisticMenu = new javax.swing.JPanel();
        statisticExportBtn = new javax.swing.JButton();
        statisticImportBtn = new javax.swing.JButton();
        statisticTableContainer = new javax.swing.JScrollPane();
        statisticTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemBtn.setText("Quản lí vật tư");
        itemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBtnActionPerformed(evt);
            }
        });

        importBtn.setText("Nhập kho");
        importBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBtnActionPerformed(evt);
            }
        });

        exportBtn.setText("Xuất kho");
        exportBtn.setToolTipText("");
        exportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportBtnMouseClicked(evt);
            }
        });

        customerBtn.setText("Khách hàng");
        customerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerBtnMouseClicked(evt);
            }
        });

        providerBtn.setText("Nhà cung cấp");
        providerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                providerBtnMouseClicked(evt);
            }
        });

        statisticBtn.setText("Thống kê");
        statisticBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statisticBtnMouseClicked(evt);
            }
        });

        addCustomerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerBtnMouseClicked(evt);
            }
        });

        editCustomerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                editCustomerBtnMouseClicked(evt);
                int row = customerTable.getSelectedRow();
                if(row >= 0){
                    PersonEntity customer = new PersonEntity();
                    customer.name = nameCustomerInput.getText();
                    customer.address = addressCustomerInput.getText();
                    customer.phone = phoneCustomertInput.getText();
                    customer.note = noteCustomerInput.getText();
                    if(customer.name == null){
                        JOptionPane.showMessageDialog(null, "Bạn không được để trống tên khách hàng");
                    } else if (customer.address == null){
                        JOptionPane.showMessageDialog(null, "Bạn không được để trống địa chỉ khách hàng");
                    } else if (customer.phone == null){
                        JOptionPane.showMessageDialog(null, "Bạn không được để trống số điện thoại khách hàng");
                    } else {
                        customer.createdAt = customerTable.getValueAt(row,4).toString();
                        customer.total = Integer.parseInt(customerTable.getValueAt(row,5).toString());
                        customers.set(row, customer);
                        customerTable.setValueAt(customer.name, row, 1);
                        customerTable.setValueAt(customer.address, row, 2);
                        customerTable.setValueAt(customer.phone, row, 3);
                        customerTable.setValueAt(customer.createdAt, row, 4);
                        customerTable.setValueAt(customer.total, row, 5);
                        customerTable.setValueAt(customer.note, row, 6);
                    }
                }
            }
        });

        deleteCustomerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = customerTable.getSelectedRow();
                if(row >= 0){
                    customers.remove(row);
                    try {
                        customerService.save(customers);
                        customerObj = customerService.generateProviderObject();
                        renderCustomerTable();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        });

        itemLabel.setText("Tên");

        codeLabel.setText("Mã hàng");

        typeItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        typeLabel.setText("Đơn vị");

        providerComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        providerLabel.setText("Nhà cung cấp");

        moneyImportLabel.setText("Giá nhập");

        moneyExportLabel.setText("Giá xuất");

        noteLabel.setText("Ghi chú");

        addItemBtn.setText("Thêm");

        editItemBtn.setText("Sửa");

        deleteItemBtn.setText("Xoá");

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên", "Mã hàng", "Đơn vị", "Nhà cung cấp", "Số lượng", "Giá nhập", "Giá xuất", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemTableContainer.setViewportView(itemTable);
        if (itemTable.getColumnModel().getColumnCount() > 0) {
            itemTable.getColumnModel().getColumn(0).setPreferredWidth(2);
            itemTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            itemTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            itemTable.getColumnModel().getColumn(3).setPreferredWidth(50);
            itemTable.getColumnModel().getColumn(4).setPreferredWidth(50);
            itemTable.getColumnModel().getColumn(5).setPreferredWidth(30);
            itemTable.getColumnModel().getColumn(6).setPreferredWidth(50);
            itemTable.getColumnModel().getColumn(7).setPreferredWidth(50);
            itemTable.getColumnModel().getColumn(8).setPreferredWidth(80);
        }

        javax.swing.GroupLayout itemMenuLayout = new javax.swing.GroupLayout(itemMenu);
        itemMenu.setLayout(itemMenuLayout);
        itemMenuLayout.setHorizontalGroup(
            itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemMenuLayout.createSequentialGroup()
                        .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(itemLabel)))
                        .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(codeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(itemCodeInput)))
                        .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(typeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(providerComp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(typeLabel)
                                .addGap(73, 73, 73)
                                .addComponent(providerLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addComponent(moneyImportInput, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(moneyExportInput, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(noteInput)
                                .addContainerGap())
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(moneyImportLabel)
                                .addGap(104, 104, 104)
                                .addComponent(moneyExportLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(noteLabel)
                                .addGap(80, 80, 80))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemMenuLayout.createSequentialGroup()
                        .addComponent(addItemBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editItemBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteItemBtn)
                        .addGap(402, 402, 402))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemMenuLayout.createSequentialGroup()
                        .addComponent(itemTableContainer)
                        .addContainerGap())))
        );
        itemMenuLayout.setVerticalGroup(
            itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemMenuLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(providerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemLabel)
                        .addComponent(codeLabel)
                        .addComponent(typeLabel)
                        .addComponent(moneyImportLabel)
                        .addComponent(moneyExportLabel)
                        .addComponent(noteLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameInput)
                    .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemCodeInput, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(typeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(providerComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(moneyImportInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(moneyExportInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(noteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(editItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemTableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        itemListStorage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        itemListLabel.setText("Tên sản phẩm");

        codeListStorage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        quantityInputStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityInputStorageActionPerformed(evt);
            }
        });

        codeListLabel.setText("Mã hàng");

        quantityLabel.setText("Số lượng");

        providerList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        providerStorageLabel.setText("Nhà cung cấp");

        storeBtn.setText("Thêm");

        editStorageBtn.setText("Sửa");
        editStorageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStorageBtnActionPerformed(evt);
            }
        });

        deleteItemStorageBtn.setText("Xoá");

        importTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        importContainer.setViewportView(importTable);

        javax.swing.GroupLayout storageMenuLayout = new javax.swing.GroupLayout(storageMenu);
        storageMenu.setLayout(storageMenuLayout);
        storageMenuLayout.setHorizontalGroup(
            storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storageMenuLayout.createSequentialGroup()
                .addGroup(storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(storageMenuLayout.createSequentialGroup()
                        .addGroup(storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storageMenuLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(itemListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(codeListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storageMenuLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(itemListStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(codeListStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(quantityInputStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGroup(storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(storageMenuLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(providerStorageLabel))
                            .addGroup(storageMenuLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(providerList, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(storageMenuLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(storeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editStorageBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteItemStorageBtn)))
                .addContainerGap(130, Short.MAX_VALUE))
            .addComponent(importContainer)
        );
        storageMenuLayout.setVerticalGroup(
            storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storageMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemListLabel)
                        .addComponent(codeListLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quantityLabel)
                        .addComponent(providerStorageLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemListStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeListStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityInputStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(providerList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStorageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteItemStorageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(importContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        itemLabel1.setText("Tên");

        codeLabel1.setText("Mã hàng");

        typeLabel1.setText("Số lượng");

        providerLabel1.setText("Khách hàng");

        addExportBtn.setText("Thêm");

        editExportBtn.setText("Sửa");

        deleteExportBtn.setText("Xoá");

        exportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên", "Mã hàng", "Khách hàng", "Ngày xuất", "Đơn vị", "Ghi chú", "Giá xuất", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        exportTableContainer.setViewportView(exportTable);
        if (exportTable.getColumnModel().getColumnCount() > 0) {
            exportTable.getColumnModel().getColumn(0).setPreferredWidth(2);
            exportTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            exportTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            exportTable.getColumnModel().getColumn(3).setPreferredWidth(50);
            exportTable.getColumnModel().getColumn(4).setPreferredWidth(50);
            exportTable.getColumnModel().getColumn(5).setPreferredWidth(30);
            exportTable.getColumnModel().getColumn(6).setPreferredWidth(50);
            exportTable.getColumnModel().getColumn(7).setPreferredWidth(50);
            exportTable.getColumnModel().getColumn(8).setPreferredWidth(80);
        }

        nameItemExportCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        codeExportCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        customerExportCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout exportMenuLayout = new javax.swing.GroupLayout(exportMenu);
        exportMenu.setLayout(exportMenuLayout);
        exportMenuLayout.setHorizontalGroup(
            exportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exportMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addExportBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editExportBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteExportBtn)
                        .addGap(402, 402, 402))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exportMenuLayout.createSequentialGroup()
                        .addComponent(exportTableContainer)
                        .addContainerGap())))
            .addGroup(exportMenuLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(exportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameItemExportCom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemLabel1))
                .addGap(48, 48, 48)
                .addGroup(exportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeExportCom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(exportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeLabel1)
                    .addComponent(quantityExportInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(exportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(providerLabel1)
                    .addComponent(customerExportCom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
        );
        exportMenuLayout.setVerticalGroup(
            exportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(exportMenuLayout.createSequentialGroup()
                        .addGroup(exportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codeLabel1)
                            .addComponent(itemLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(exportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codeExportCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameItemExportCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(exportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(exportMenuLayout.createSequentialGroup()
                            .addComponent(providerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(customerExportCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(exportMenuLayout.createSequentialGroup()
                            .addComponent(typeLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(quantityExportInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(exportMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(editExportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addExportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteExportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(exportTableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        itemLabel2.setText("Tên");

        codeLabel2.setText("Địa chỉ");

        typeLabel2.setText("Số điện thoại");

        providerLabel2.setText("Ghi chú");

        addCustomerBtn.setText("Thêm");

        editCustomerBtn.setText("Sửa");

        deleteCustomerBtn.setText("Xoá");

        renderCustomerTable();
        customerTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
               try{
                   nameCustomerInput.setText(customerTable.getValueAt(customerTable.getSelectedRow(), 1).toString());
                   addressCustomerInput.setText(customerTable.getValueAt(customerTable.getSelectedRow(), 2).toString());
                   phoneCustomertInput.setText(customerTable.getValueAt(customerTable.getSelectedRow(), 3).toString());
                   noteCustomerInput.setText(customerTable.getValueAt(customerTable.getSelectedRow(), 6).toString());
               } catch (Exception e){
                   nameCustomerInput.setText("");
                   addressCustomerInput.setText("");
                   phoneCustomertInput.setText("");
                   noteCustomerInput.setText("");
               }
            }
        });

        customerTableContainer.setViewportView(customerTable);
        if (customerTable.getColumnModel().getColumnCount() > 0) {
            customerTable.getColumnModel().getColumn(0).setPreferredWidth(2);
            customerTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            customerTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            customerTable.getColumnModel().getColumn(3).setPreferredWidth(50);
            customerTable.getColumnModel().getColumn(4).setPreferredWidth(50);
            customerTable.getColumnModel().getColumn(5).setPreferredWidth(30);
            customerTable.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        javax.swing.GroupLayout customerMenuLayout = new javax.swing.GroupLayout(customerMenu);
        customerMenu.setLayout(customerMenuLayout);
        customerMenuLayout.setHorizontalGroup(
            customerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerMenuLayout.createSequentialGroup()
                        .addComponent(customerTableContainer)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerMenuLayout.createSequentialGroup()
                        .addGroup(customerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerMenuLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addCustomerBtn)
                                .addGap(18, 18, 18)
                                .addComponent(editCustomerBtn))
                            .addGroup(customerMenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addGroup(customerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameCustomerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemLabel2))
                                .addGap(45, 45, 45)
                                .addGroup(customerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressCustomerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerMenuLayout.createSequentialGroup()
                                .addComponent(deleteCustomerBtn)
                                .addGap(402, 402, 402))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerMenuLayout.createSequentialGroup()
                                .addGroup(customerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeLabel2)
                                    .addComponent(phoneCustomertInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(customerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noteCustomerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(providerLabel2))
                                .addGap(78, 78, 78))))))
        );
        customerMenuLayout.setVerticalGroup(
            customerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerMenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(customerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLabel2)
                    .addComponent(typeLabel2)
                    .addComponent(itemLabel2)
                    .addComponent(providerLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(customerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressCustomerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneCustomertInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noteCustomerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameCustomerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(customerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(editCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(customerTableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        itemLabel4.setText("Tên");

        codeLabel4.setText("Địa chỉ");

        typeLabel4.setText("Số điện thoại");

        providerLabel4.setText("Ghi chú");

        addProviderBtn.setText("Thêm");

        editProviderBtn.setText("Sửa");

        deleteProviderBtn.setText("Xoá");


        providerTable.setModel(new javax.swing.table.DefaultTableModel(
                providerService.generateProviderObject(),
                new String [] {
                    "STT", "Tên", "Địa chỉ", "Số điện thoại", "Ngày tạo", "Tổng tiền", "Ghi chú"
                }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        providerTableContainer.setViewportView(providerTable);
        if (providerTable.getColumnModel().getColumnCount() > 0) {
            providerTable.getColumnModel().getColumn(0).setPreferredWidth(2);
            providerTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            providerTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            providerTable.getColumnModel().getColumn(3).setPreferredWidth(50);
            providerTable.getColumnModel().getColumn(4).setPreferredWidth(50);
            providerTable.getColumnModel().getColumn(5).setPreferredWidth(30);
            providerTable.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        javax.swing.GroupLayout providerMenuLayout = new javax.swing.GroupLayout(providerMenu);
        providerMenu.setLayout(providerMenuLayout);
        providerMenuLayout.setHorizontalGroup(
            providerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(providerMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(providerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, providerMenuLayout.createSequentialGroup()
                        .addComponent(providerTableContainer)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, providerMenuLayout.createSequentialGroup()
                        .addGroup(providerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(providerMenuLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addProviderBtn)
                                .addGap(18, 18, 18)
                                .addComponent(editProviderBtn))
                            .addGroup(providerMenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addGroup(providerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameProviderInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemLabel4))
                                .addGap(45, 45, 45)
                                .addGroup(providerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codeLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressProviderInput, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(providerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(providerMenuLayout.createSequentialGroup()
                                .addComponent(deleteProviderBtn)
                                .addGap(402, 402, 402))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, providerMenuLayout.createSequentialGroup()
                                .addGroup(providerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeLabel4)
                                    .addComponent(phoneProviderInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(providerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noteProviderInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(providerLabel4))
                                .addGap(78, 78, 78))))))
        );
        providerMenuLayout.setVerticalGroup(
            providerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(providerMenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(providerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLabel4)
                    .addComponent(typeLabel4)
                    .addComponent(itemLabel4)
                    .addComponent(providerLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(providerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressProviderInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneProviderInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noteProviderInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameProviderInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(providerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(editProviderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProviderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteProviderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(providerTableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        statisticExportBtn.setText("Thống kê xuất hàng");

        statisticImportBtn.setText("Thống kê nhập hàng");

        statisticTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên", "Mã hàng", "Số lượng", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        statisticTableContainer.setViewportView(statisticTable);
        if (statisticTable.getColumnModel().getColumnCount() > 0) {
            statisticTable.getColumnModel().getColumn(0).setPreferredWidth(2);
            statisticTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            statisticTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            statisticTable.getColumnModel().getColumn(3).setPreferredWidth(50);
            statisticTable.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        javax.swing.GroupLayout statisticMenuLayout = new javax.swing.GroupLayout(statisticMenu);
        statisticMenu.setLayout(statisticMenuLayout);
        statisticMenuLayout.setHorizontalGroup(
            statisticMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statisticMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statisticMenuLayout.createSequentialGroup()
                        .addComponent(statisticTableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statisticMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(statisticExportBtn)
                        .addGap(135, 135, 135)
                        .addComponent(statisticImportBtn)
                        .addGap(337, 337, 337))))
        );
        statisticMenuLayout.setVerticalGroup(
            statisticMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticMenuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(statisticMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statisticImportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statisticExportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(statisticTableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(importBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(providerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statisticBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(storageMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(exportMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(customerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(providerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(statisticMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(importBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(providerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(statisticBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(itemMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(69, Short.MAX_VALUE)
                    .addComponent(storageMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(exportMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(21, 21, 21)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(customerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(21, 21, 21)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(providerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(statisticMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBtnActionPerformed
        changeView(this.storageMenu);
    }//GEN-LAST:event_importBtnActionPerformed

    private void quantityInputStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityInputStorageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityInputStorageActionPerformed

    private void editStorageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStorageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editStorageBtnActionPerformed

    private void itemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBtnActionPerformed
        changeView(this.itemMenu);
    }//GEN-LAST:event_itemBtnActionPerformed

    private void exportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportBtnMouseClicked
        changeView(this.exportMenu);
    }//GEN-LAST:event_exportBtnMouseClicked

    private void customerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerBtnMouseClicked
        changeView(this.customerMenu);
    }//GEN-LAST:event_customerBtnMouseClicked

    private void providerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_providerBtnMouseClicked
        changeView(this.providerMenu);
    }//GEN-LAST:event_providerBtnMouseClicked

    private void statisticBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticBtnMouseClicked
        changeView(this.statisticMenu);
    }//GEN-LAST:event_statisticBtnMouseClicked

    private void addCustomerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerBtnMouseClicked
        PersonEntity customer = new PersonEntity();
        customer.name = nameCustomerInput.getText();
        customer.address = addressCustomerInput.getText();
        customer.phone = phoneCustomertInput.getText();
        customer.note = noteCustomerInput.getText();
        if(customer.name == null){
            JOptionPane.showMessageDialog(null, "Bạn không được để trống tên khách hàng");
        } else if (customer.address == null){
            JOptionPane.showMessageDialog(null, "Bạn không được để trống địa chỉ khách hàng");
        } else if (customer.phone == null){
            JOptionPane.showMessageDialog(null, "Bạn không được để trống số điện thoại khách hàng");
        } else {
            customer.createdAt = new SimpleDateFormat("yyyy/MM/dd").format(Calendar.getInstance().getTime());
            customer.total = 0;
            customers.add(customer);
            Object[] o = new Object[7];
            o[0] = customers.size();
            o[1] = customer.name;
            o[2] = customer.address;
            o[3] = customer.phone;
            o[4] = customer.createdAt;
            o[5] = customer.total;
            o[6] = customer.note;
            DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
            model.addRow(o);
        }
    }//GEN-LAST:event_addCustomerBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStorage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JButton addExportBtn;
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton addProviderBtn;
    private javax.swing.JTextField addressCustomerInput;
    private javax.swing.JTextField addressProviderInput;
    private javax.swing.JComboBox<String> codeExportCom;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JLabel codeLabel1;
    private javax.swing.JLabel codeLabel2;
    private javax.swing.JLabel codeLabel4;
    private javax.swing.JLabel codeListLabel;
    private javax.swing.JComboBox<String> codeListStorage;
    private javax.swing.JButton customerBtn;
    private javax.swing.JComboBox<String> customerExportCom;
    private javax.swing.JPanel customerMenu;
    private javax.swing.JTable customerTable;
    private javax.swing.JScrollPane customerTableContainer;
    private javax.swing.JButton deleteCustomerBtn;
    private javax.swing.JButton deleteExportBtn;
    private javax.swing.JButton deleteItemBtn;
    private javax.swing.JButton deleteItemStorageBtn;
    private javax.swing.JButton deleteProviderBtn;
    private javax.swing.JButton editCustomerBtn;
    private javax.swing.JButton editExportBtn;
    private javax.swing.JButton editItemBtn;
    private javax.swing.JButton editProviderBtn;
    private javax.swing.JButton editStorageBtn;
    private javax.swing.JButton exportBtn;
    private javax.swing.JPanel exportMenu;
    private javax.swing.JTable exportTable;
    private javax.swing.JScrollPane exportTableContainer;
    private javax.swing.JButton importBtn;
    private javax.swing.JScrollPane importContainer;
    private javax.swing.JTable importTable;
    private javax.swing.JButton itemBtn;
    private javax.swing.JTextField itemCodeInput;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JLabel itemLabel1;
    private javax.swing.JLabel itemLabel2;
    private javax.swing.JLabel itemLabel4;
    private javax.swing.JLabel itemListLabel;
    private javax.swing.JComboBox<String> itemListStorage;
    private javax.swing.JPanel itemMenu;
    private javax.swing.JTable itemTable;
    private javax.swing.JScrollPane itemTableContainer;
    private javax.swing.JTextField moneyExportInput;
    private javax.swing.JLabel moneyExportLabel;
    private javax.swing.JTextField moneyImportInput;
    private javax.swing.JLabel moneyImportLabel;
    private javax.swing.JTextField nameCustomerInput;
    private javax.swing.JTextField nameInput;
    private javax.swing.JComboBox<String> nameItemExportCom;
    private javax.swing.JTextField nameProviderInput;
    private javax.swing.JTextField noteCustomerInput;
    private javax.swing.JTextField noteInput;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JTextField noteProviderInput;
    private javax.swing.JTextField phoneCustomertInput;
    private javax.swing.JTextField phoneProviderInput;
    private javax.swing.JButton providerBtn;
    private javax.swing.JComboBox<String> providerComp;
    private javax.swing.JLabel providerLabel;
    private javax.swing.JLabel providerLabel1;
    private javax.swing.JLabel providerLabel2;
    private javax.swing.JLabel providerLabel4;
    private javax.swing.JComboBox<String> providerList;
    private javax.swing.JPanel providerMenu;
    private javax.swing.JLabel providerStorageLabel;
    private javax.swing.JTable providerTable;
    private javax.swing.JScrollPane providerTableContainer;
    private javax.swing.JTextField quantityExportInput;
    private javax.swing.JTextField quantityInputStorage;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JButton statisticBtn;
    private javax.swing.JButton statisticExportBtn;
    private javax.swing.JButton statisticImportBtn;
    private javax.swing.JPanel statisticMenu;
    private javax.swing.JTable statisticTable;
    private javax.swing.JScrollPane statisticTableContainer;
    private javax.swing.JPanel storageMenu;
    private javax.swing.JButton storeBtn;
    private javax.swing.JComboBox<String> typeItem;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel typeLabel1;
    private javax.swing.JLabel typeLabel2;
    private javax.swing.JLabel typeLabel4;
    private List<PersonEntity> providers;
    private PersonService providerService;
    private List<PersonEntity> customers;
    private PersonService customerService;
    // End of variables declaration//GEN-END:variables
}
